spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


logging:
  level:
    root: info
    com.example.demo: debug
    org.hibernate.type.descriptor.sql: trace
